[tools]
"cargo:eza" = "latest"
"cargo:tree-sitter-cli" = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
"go:github.com/d-kuro/gwq/cmd/gwq" = "latest"
neovim = "latest"
node = "24"
"npm:agent-browser" = "0.33.2"
pnpm = "latest"
yarn = "latest"

[settings]
idiomatic_version_file_enable_tools = []
