export GPG_TTY=$(tty)

# git branch show
autoload -Uz vcs_info add-zsh-hook
autoload -U colors && colors

setopt prompt_subst
zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:*' check-for-changes true
zstyle ':vcs_info:*' unstagedstr ' *'
zstyle ':vcs_info:*' stagedstr ' +'
zstyle ':vcs_info:git*' formats "%{$fg[blue]%}%b%u%c%{$reset_color%}"
zstyle ':vcs_info:git*' actionformats "%{$fg[blue]%}%b|%a%u%c%{$reset_color%}"

# https://vincent.bernat.ch/en/blog/2019-zsh-async-vcs-info
_vbe_vcs_info() {
  cd -q $1
  vcs_info
  print ${vcs_info_msg_0_}
}

source ~/.config/async.zsh
async_init
async_start_worker vcs_info
async_register_callback vcs_info _vbe_vcs_info_done

_vbe_vcs_info_done() {
  local stdout=$3
  vcs_info_msg_0_=$stdout
  zle reset-prompt
}

_vbe_vcs_precmd() {
  async_flush_jobs vcs_info
  async_job vcs_info _vbe_vcs_info $PWD
}

add-zsh-hook precmd _vbe_vcs_precmd

# add-zsh-hook precmd vcs_info
PROMPT=$'
%(?..%F{red}%?%f )%~ ${vcs_info_msg_0_}
%F{magenta}\U27E9%f '

if [[ "$OSTYPE" == darwin* ]]; then
  # llvm
  export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
  export LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

  # mysql
  export PATH="/usr/local/mysql/bin:$PATH"
fi

# Private env
[ -f ~/.env ] && source ~/.env

# Work-specific zshrc
[ -f ~/.zshrc-work ] && source ~/.zshrc-work

# ALIAS
alias "ls"="eza"
alias "l"="eza -l --classify=auto --group-directories-first"

alias gadd="
git ls-files -m -o --exclude-standard |
  fzf -m --preview 'git diff --color=always {} 2>/dev/null || cat {}' |
  xargs git add
"

alias gunstage="
git diff --cached --name-only |
  fzf -m --preview 'git diff --cached --color=always {} 2>/dev/null || cat {}' |
  xargs git restore --staged
"

# FUNCS
proj() {
  local dir
  dir=$(zoxide query -l | fzf --preview 'eza -l --color=always {}') || return
  pushd "$dir" > /dev/null
  nvim .
  popd > /dev/null
}

[[ -r "$HOME/.local/bin/env" ]] && source "$HOME/.local/bin/env"

alias codx="codex --yolo"
alias clawd="claude --dangerously-skip-permissions --worktree"

# secrets
[[ -r "$HOME/.config/zsh/secrets.zsh" ]] && source "$HOME/.config/zsh/secrets.zsh"

# gwq
(( $+commands[gwq] )) && source <(gwq completion zsh)

# gwq shorcut
gwa() {
  if (( $# < 2)); then
    print -u2 "usage: gwa <ticket> <command> [args...]"
    return 2
  fi

  local ticket="$1"
  shift

  if ! command git worktree list --porcelain |
    command grep -Fqx "branch refs/heads/$ticket"; then

    if command git show-ref --verify --quiet "refs/heads/$ticket"; then
      command gwq add -- "$ticket" || return
    else 
      command gwq add -b -- "$ticket" || return
    fi
  fi

  command gwq exec "$ticket" -- "$@"
}
