tap "anomalyco/tap"
tap "antoniorodr/memo"
tap "openclaw/tap"
tap "steipete/tap"
# Browser automation CLI for AI agents
brew "agent-browser"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Cross-platform make
brew "cmake"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# GitHub command-line tool
brew "gh"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# Deep clean and optimize your Mac
brew "mole"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Parser generator tool
brew "tree-sitter-cli"
# Process YAML, JSON, XML, CSV and properties documents from the CLI
brew "yq"
# Programming language designed for robustness, optimality, and clarity
brew "zig"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# OpenAI's coding agent that runs in your terminal
cask "codex"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Minimal installer for conda
cask "miniconda"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
go "cmd/go"
go "cmd/gofmt"
cargo "wasm-bindgen-cli"
npm "vercel"
